var facts = [
'Pamela Anderson Lee is Canadaâ€™s Centennial Baby, being the first baby born on the centennial anniversary of Canadaâ€™s independence.',
'Pinocchio is Italian for â€œpine head.â€',
'When possums are playing â€˜possumâ€™, they are not â€œplaying.â€ They actually pass out from sheer terror.',
'Whoâ€™s that playing the piano on the â€œMad About Youâ€ theme? Paul Reiser himself.',
'Winston Churchill was born in a ladiesâ€™ room during a dance.',
'Most lipstick contains fish scales!',
'Donald Duck comics were banned from Finland because he doesnâ€™t wear pants!',
'There are more than 10 million bricks in the Empire State Building!',
'Camels have three eyelids to protect themselves from blowing sand!',
'The placement of a donkeyâ€™s eyes in itsâ€™ heads enables it to see all four feet at all times!',
'The average American/Canadian will eat about 11.9 pounds of cereal per year!',
'Over 1000 birds a year die from smashing into windows!',
'The state of Florida is bigger than England!',
'Dolphins sleep with one eye open!',
'In the White House, there are 13,092 knives, forks and spoons!',
'Recycling one glass jar, saves enough energy to watch T.V for 3 hours!',
'Owls are one of the only birds who can see the color blue!',
'Honeybees have a type of hair on their eyes!',
'A jellyfish is 95 percent water!',
'In Bangladesh, kids as young as 15 can be jailed for cheating on their finals!',
'Humans are the only primates that donâ€™t have pigment in the palms of their hands.',
'Months that begin on a Sunday will always have a â€˜Friday the 13thâ€™.',
'The fingerprints of koala bears are virtually indistinguishable from those of humans, so much so that they can be easily confused at a crime scene.',
'The mask worn by Michael Myers in the original â€œHalloweenâ€ was actually a Captain Kirk mask painted white.',
'Only one person in two billion will live to be 116 or older.',
'Dr. Jack Kevorkian first patient has Alzheimerâ€™s disease.',
'Fictional/horror writer Stephen King sleeps with a nearby light on to calm his fear of the dark. ',
'Itâ€™s possible to lead a cow upstairs but not downstairs.',
'The very first song played on MTV was â€˜Video Killed The Radio Starâ€™ by the Buggles.',
'Americans travel 1,144,721,000 miles by air every day',
'The the U.S. you dial â€™911 In Stockholm, Sweden you dial 90000',
'38% of American men say they love their cars more than women',
'The U.S. military operates 234 golf courses',
'100% of lottery winners do gain weight',
'Bullet proof vests, fire escapes, windshield wipers, and laser printers were all invented by women',
'A cat has 32 muscles in each ear.',
'A duckâ€™s quack doesnâ€™t echo, and no one knows why.',
'Cats urine glows under a black light.',
'In every episode of Seinfeld there is a Superman somewhere.',
'Lorne Greene had one of his nipples bitten off by an alligator while he was host of â€œLorne Greeneâ€™s Wild Kingdom.â€',
'Rhode Island is the only state which the hammer throw is a legal high school sport.',
'The average lifespan of an eyelash is five months.',
'A spider has transparent blood.',
'Every acre of American crops harvested contains 100 pounds of insects.',
'Prince Charles is an avid collecter of toilet seats.',
'The most common street name in the U.S. is Second Street.',
'Tehran is the most expensive city on earth.',
'The sweat drops drawn in cartoon comic strips are called pleuts.',
'Babies are most likely to be born on Tuesdays.',
'The HyperMart outside of Garland Texas has 58 check-outs.',
'The Minneapolis phone book has 21 pages of Andersons.',
'In the 1980s American migraines increased by 60%.',
'Poland is the â€œstolen car capital of the worldâ€.',
'Jefferson invented the dumbwaiter, the monetary system, and the folding attic ladder.',
'The S in Harry S. Truman did not stand for anything.',
'In Miconesia, coins are 12 feet across.',
'A horse can look forward with one eye and back with the other.',
'Shakespeare is quoted 33,150 times in the Oxford English dictionary.',
'The word Pennsylvania is misspelled on the Liberty Bell.',
'NBA superstar Michael Jordan was originally cut from his high school basketball team.',
'You spend 7 years of your life in the bathroom.',
'A family of 26 could go to the movies in Mexico city for the price of one in Tokyo.',
'10,000 Dutch cows pass through the Amsterdam airport each year.',
'Approximately every seven minutes of every day, someone in an aerobics class pulls their hamstring.',
'Simplistic passwords contribute to over 80% of all computer password break-ins.',
'The top 3 health-related searches on the Internet are (in this order): Depression, Allergies, & Cancer.',
'Dentists have recommended that a toothbrush be kept at least 6 feet away from a toilet to avoid airborne particles resulting from the flush.',
'Most dust particles in your house are made from dead skin.',
'Venus is the only planet that rotates clockwise.',
'Oak trees do not produce acorns until they are fifty years of age or older.',
'The first owner of the Marlboro company died of lung cancer.',
'All US Presidents have worn glasses; some just didnâ€™t like being seen wearing them in public.',
'Mosquito repellents donâ€™t repel. They hide you. The spray blocks the mosquitoâ€™s sensors so they donâ€™t know youâ€™re there.',
'Walt Disney was afraid of mice.',
'The site with the highest number of women visitors between the age of 35 and 44 years old: Alka-Seltzer.com',
'The king of hearts is the only king without a mustache.',
'Pearls melt in vinegar.',
'It takes 3,000 cows to supply the NFL with enough leather for a yearâ€™s supply of footballs.',
'Thirty-five percent of people who use personal ads for dating are already married.',
'The 3 most valuable brand names on earth are Marlboro, Coca-Cola, and Budweiser (in that order).',
'Cost of raising a medium-sized dog to the age of 11: Â£4000',
'The name Jeep came from the abbreviation used in the army for the â€œGeneral Purposeâ€ vehicle, G.P.',
'The cruise liner Queen Elizabeth II, moves only six inches for each gallon of fuel that it burns.',
'A Saudi Arabian woman can get a divorce if her husband doesnâ€™t give her coffee.',
'The dot over the letter â€˜iâ€™ is called a tittle.',
'Humans are the only primates that donâ€™t have pigment in the palms of their hands.',
'Itâ€™s possible to lead a cow upstairsâ€¦but not downstairs.',
'Dogs have four toes on their hind feet, and five on their front feet.',
'A cockroach will live nine days without itâ€™s head, before it starves to death.',
'Butterflies taste with their feet.',
'Elephants are the only mamals that canâ€™t jump.',
'Starfish donâ€™t have brains.',
'Polar bears are left handed.',
'A duckâ€™s quack doesnâ€™t echo, and no one knows why.',
'An ostrichâ€™s eye is bigger that itâ€™s brain.',
'The fingerprints of koala bears are virtually indistinguishable from those of humans, so much so that they could be confused at a crime scene.',
'Snails can sleep for 3 years without eating',
'Porcupines float in water.',
'Armadillos are the only animal besides humans that can get leprosy.',
'Many hamsters only blink one eye at a time.',
'A pregnant goldfish is called a twit.',
'A male emperor moth can smell a female emperor moth up to 7 miles away.',
'A giraffe can clean its ears with its 21-inch tongue!',
'Orcas (killer whales) kill sharks by torpedoing up into to sharkâ€™s stomach from underneath, causing the shark to explode.',
'If NASA sent birds into space they would soon die; they need gravity to swallow.',
'Emus and kangaroos cannot walk backwards, and are on the Australian coat of arms for that reason.',
'Certain frogs can be frozen solid, then thawed, and survive.',
'Catâ€™s urine glows under a black light.',
'A shark can detect one part of blood in 100 million parts of water.',
'A rat can last longer without water than a camel.',
'To escape the grip of a crocodileâ€™s jaws, push your thumbs into its eyeballs â€“ it will let you go instantly.',
'A crocodile canâ€™t stick itâ€™s tongue out.',
'A shrimpâ€™s heart is in itâ€™s head.',
'A pregnant goldfish is called a twit.',
'Rats and horses canâ€™t vomit.',
'A duckâ€™s quack doesnâ€™t echo, and no one knows why.',
'Most lipstick contains fish scales.',
'A crocodile canâ€™t move its tongue and cannot chew. Its digestive juices are so strong that it can digest a steel nail.',
'Rats breed so quickly that in just 18 months, 2 rats could have created over 1 million relatives.',
'The blue whale can produce the loudest sound of any animal. At 188 decibels, the noise can be detected over 800 kilometres away.',
'Horses and cows sleep while standing up.',
'Giant Arctic jellyfish have tentacles that can reach over 36 metres in length.',
'Locusts have leg muscles that are about 1000 times more powerful than an equal weight of human muscle.',
'Hummingbirds are so agile and have such good control that they can fly backwards.',
'Instead of bones, sharks have a skeleton made from cartilage.',
'Insects such as bees, mosquitoes and cicadas make noise by rapidly moving their wings.',
'The horn of a rhinoceros is made from compacted hair rather than bone or another substance.',
'Sharks lay the biggest eggs in the world.',
'Even when a snake has its eyes closed, it can still see through its eyelids.',
'Unlike humans, sheep have four stomachs, each one helps them digest the food they eat.',
'Despite the white, fluffy appearance of Polar Bears fur, it actually has black skin.',
'As well as being a famous Looney Tunes character, the Tasmanian Devil is a real animal that is only found in the wild in Tasmania, Australia. It is the largest carnivorous marsupial in the world.',
'The average housefly only lives for 2 or 3 weeks.',
'Mosquitoes can be annoying insects but did you know that itâ€™s only the female mosquito that actually bites humans.',
'Cats use their whiskers to check whether a space is too small for them to fit through or not.',
'There are presently over a million animal species upon planet earth. ',
'The reptiles have 6,000 species crawling in their habitats; and more are discovered each year. ',
'There are over 70,000 types of spiders spinning their webs in the world. ',
'Well, there are 3,000 kinds of lice. Yes, it is the lice we are prone to get due to lack of hair hygiene. ',
'This is a mind-boggling fact â€“ for each of the 600 million people there is about 200 million insects crawling, flyingâ€¦ ',
'Mammals are the only creatures that have flaps around their ears. ',
'The world has approximately one billion cattle, of which about 200 million belong to India. ',
'The life of a housefly is only 14 days. ',
'A dog was the first animal to up in space. ',
'A sheep, a duck and a rooster were the first animals to fly in a hot air balloon. The oldest breed of a dog known to mankind is the â€˜Salukiâ€™. ',
'An ostrich is the fastest bird and can run up to 70 km/h. ',
'Never get a camel angry, for he or she will spit at you. ',
'There are crabs that are the size of a pea. There are known as â€˜Pea Crabsâ€™. ',
'The lifespan of 75 percent of wild birds is 6 months. ',
'Denmark has twice as many pigs as there are people. ',
'You do not need cotton buds to clean a giraffe ears. It can do so with its own 50cm-tongue. ',
'Want to known the appetite of a South American Giant Anteater? Well it eats over 30,000 ants, per day. ',
'The sailfish can swim at the speed of 109 km/h, making it the fastest swimmer. ',
'The Sea Horse is the slowest fish, drifting at approximately 0.016 km/h. ',
'The small car on the road is probably the size of the heart of a blue whale. ',
'The length of an elephant is the same as the tongue of a blue whale. ',
'The crocodileâ€™s tongue is unmovable, as it is attached to the roof of its mouth.',
'No one really knows when donuts were invented or who invented them.',
'Apples, potatoes, and onions all taste the same when eaten with your nose plugged.',
'When an egg floats in water, it is â€œoffâ€ and should not be eaten.',
'The consumption of natural vanilla causes the body to release catecholamines (including adrenalin) â€“ for this reason it is considered to be mildly addictive.',
'Banana trees are not actually trees â€“ they are giant herbs.',
'Ketchup was originally a fish sauce originating in the orient',
'7-Up â€“ invented in 1920 contained Lithium â€“ the drug commonly prescribed now to sufferers of bi-polar disorder.',
'In Tibet, a common drink is butter tea â€“ it is made from yak butter, salt, and tea.',
'Nutritious food costs 10 times as much as junk food.',
'Grocers donâ€™t have to tell you where your salad comes from.',
'Chicken today contains 266 percent more fat than it did 40 years ago.',
'Chewing gum while peeling onions will keep you from crying!',
'Smelling bananas and/or green apples (smelling, not eating) can help you lose weight!',
'Eating lemons make you live longer.',
'Eating one meal of fish a week reduces your chances of getting a heart attack by 50%.',
'The first meal on the moon was roast turkey, eaten by Niel Armstrong and Buzz Aldrin.',
'A typical banana travels 4,000 miles before being eaten.',
'Coffee is the worldâ€™s most recognizable smell.',
'Carrots have zero fat content.',
'When honey is swallowed, it enters the blood stream within a period of 20 minutes.',
'Coconut water can be used in an emergency as a substitute for blood plasma.',
'Orange Juice naturally contains a small amount of alcohol.',
'Eggs contain most of the recognised vitamins with the exception of vitamin C.',
'Lemons contain more sugar than strawberries',
'Strawberries are the only fruit which has its seeds on its outer skin.',
'Grapes explode when you put them in the microwave. You have been warned!',
'Apples, potatoes, and onions all taste the same when eaten with your nose plugged.',
'There are more than 7,000 varieties of apples grown in the world.',
'Peanuts can be used for a component to make Dynamite.',
'Chocolate can kill dogs; it directly affects their heart and nervous system.',
'A watermelon is over 92% water by weight.',
'Lettuce is a member of the sunflower family.',
'Darker Green lettuce leaves are more nutritious than lighter green leaves.',
'Americans eat about 30 pounds of lettuce every year. Thatâ€™s about five times more than what we ate in the early 1900s.',
'In the United States, lettuce is the second most popular fresh vegetable.',
'Almost all lettuce is packed right in the field.',
'About 25% of all iceberg lettuce is made into fresh cut salads.',
'There are over 500 different types of bananas. That means if you ate a different kind of banana everyday, it would take almost a year and a half to eat every one!',
'The banana plant can grow as high as 20 feet tall. Thatâ€™s as big as a two-story house!',
'Bananas are about 99.5% fat free.',
'Bananas are a great source of potassium. Potassium helps build muscle power and keeps your body fluids in balance.',
'Bananaâ€™s are most likely the first fruit ever to be grown on a farm.',
'Every time you lick a stamp, youâ€™re consuming 1/10 of a calorie.',
'Your stomach has to produce a new layer of mucus every two weeks otherwise it will digest itself',
'Nutmeg is extremely poisonous if injected intravenously.',
'Pearls melt in vinegar.',
'Honey is the only food that doesnâ€™t spoil.',
'If you put a raisin in a glass of champagne, it will keep floating to the top and sinking to the bottom.',
'Coca Cola was originally green.',
'40% of McDonaldâ€™s profits come from the sales of Happy Meals.',
'Every person has a unique tongue print.',
'Golf the only sport played on the moon â€“ on 6 February 1971 Alan Shepard hit a golf ball.',
'The first World Series was played between Pittsburgh and Boston in 1903 and was a nine-game series. Boston won the series 5-3.',
'About 42,000 tennis balls are used in the plus-minus 650 matches in the Wimbledon Championship.',
'The first puck ever used in a hovkey game was a frozen piece of cow crap.',
'The New York Yankees have won 26 World Series titles, which is more than any other team.',
'Fishing is the biggest participant sport in the world.',
'It takes 3,000 cows to supply the NFL with enough leather for a yearâ€™s supply of footballs.',
'Shaquille Oâ€™Neal wears size 22 shoes. He puts on a brand new pair before every game.',
'Baltimore Orioles shortstop Cal Ripken, Jr. didnâ€™t miss a game in 16 years. He played in 2,632 consecutive games from April 30, 1982 to Sept. 19, 1998.',
'Before 1859, umpires sat in a padded rocking chair behind the catcher',
'More than 1,800 medals are awarded at the Olympics.',
'Soccer is the most attended or watched sport in the world.',
'The Boston Celtics have won the most NBA championships (17), including seven straight from 1960 to 1966.',
'Pittsburgh is the only U.S. city with 3 sports teams that wear the same colors.',
'Average lifespan of a major league baseball: 5 pitches.',
'Boxing became a legal sport in 1901.',
'A forfeited game in baseball is recorded as 9-0.',
'Babe Ruth wore a cabbage leaf under his cap to keep him cool! He changed it every 2 innings!',
'The record for the most major league baseball career innings is held by Cy Young, with 7,356 innings.',
'Archery is the national sport in Bhutan,a Buddhist country in Asia.',
'The fastest serve in a game of tennis was in 1963 by Michael Sangster. It was clocked at 154 mile per hour.',
'South Korea is the birthplace of taekwondo, an olympic sport since 2000.',
'Before the turn of the century, prize fighters fought bare fisted. Matches sometimes lasted more than one hundred rounds and were counted by knock outs.',
'The oldest continuous trophy in sports is the Americaâ€™s Cup. It started in 1851, with Americans winning for a straight 132 years until Australia took the Cup in 1983.',
'Pitcher Nolan Ryan played 27 seasons in major league baseball and struck out more batters in his career than any other pitcher',
'To wear a â€œvisorâ€ on your helmet in the NFL, you have to have a doctors note. Almost all the visors in the NFL are prescription.',
'If a horse wins a race â€œhands downâ€ it means the jockey never raised his whip during the race.',
'Sports command the biggest television audiences, led by the summer Olympics, World Cup Football and Formula One racing.',
'Golf balls can reach speeds of 170 miles an hour.',
'Although 24 out of the 30 current National Hockey League teams are located in the United States, all NHL jerseys are manufactured in Canada.',
'Korfball is the only sport played with mixed teams, consisting of 4 men and 4 women.',
'Official baseball rules state that an umpire may not be replaced during a game except if he becomes ill, injured, or if he dies.',
'Kareem Abdul-Jabbar, who played 20 seasons in the NBA, holds the record for most points scored in a career with 38,387.',
'The Chicago Bulls have won all six NBA Finals in which theyâ€™ve appeared.',
'Approximately one out of four injuries by athletes involve the wrist and hand.',
'In bowling, three strikes in a row was called a turkey. The term originated in the 1800s when at holiday time, the first member of a team to score three strikes in a row won a free turkey.',
'The national sport of Japan is sumo wrestling.',
'In the 1930s, American track star Jesse Owens used to race against horses and dogs to earn a living.',
'On average, it is estimated that females injure themselves ten times more than males do while playing sports',
'On March 2, 1962, Philadelphia center Wilt Chamberlain scored 100 points in one game against New York. That is the most one player has ever scored in one game.',
'Wild Bill Hickok was killed playing poker, holding two pairs â€“ aces and eights, which has become known as â€˜Dead Manâ€™s Hand.',
'Morihei Ueshiba, founder of Aikido, once pinned an opponent using only a single finger.',
'Billiards used to be so popular at one time that cigarette cards were issued featuring players.',
'Gold medals havenâ€™t been pure gold in 96 years. The 1912 Olympics was the last time that gold medals were solid gold. Ever since, theyâ€™ve been silver with gold plating.',
'During the hundred days of the opening games at the Colosseum in Rome, in 80 A.D., over 5,000 animals were killed, including elephants, tigers, lions, elks, hyenas, hippopotamuses, and giraffes.',
'A perfect game in baseball is one in which the same player pitches the entire game without allowing any player of the opposing team to reach first base',
'Kite flying is a professional sport in Thailand.',
'The sport Lacrosse was initially played by Native American Indians. They played the sport to prepare for war.',
'The Ouija board is named for the French and German words for yes â€“ oui and ja.',
'The San Diego Chargers of the NFL are named after a credit card.',
'Golfers use an estimated $800 million worth of golf balls annually.',
'Gymnasiums were introduced in 900BC and Greek athletes practised in the nude to the accompaniment of music. They also performed naked at the Olympic Games.',
'The velocity of a pitched baseball is about 8 mph faster as it leaves the pitcherâ€™s hand than when it reaches home plate.',
'In 1905, 18 men died from injuries sustained on the football field. President Theodore Roosevelt stepped in and instituted safety measures to make the game safer.',
'There are 318,979,564,000 ways of playing the first four turns in a game of chess. There are 169,518,829,100,544,000,000,000,000,000 ways of playing the first ten turns of a game of chess.',
'If the air conditioning at the Astrodome in Houston were turned off, it would rain inside the stadium due to the entrance of humid air.',
'The first professional football team to sport an insignia on their helmets was the Los Angeles Rams in 1950, who hand painted yellow horns on their blue leather helmets.',
'The distance between the pitcherâ€™s rubber and home plate in baseball is 60 feet, 6 inches',
'The first modern Olympic Games were held in Athens, Greece in 1896. There were 311 male but no female competitors.',
'The first players elected to Baseball Hall of Fame were Ty Cobb, Babe Ruth, Honus Wagner, Christy Mathewson & Walter Johnson in 1936',
'Chuck Norris can build a house from the roof down',
'When Alexander Bell invented the telephone he had 3 missed calls from Chuck Norris',
'Fear of spiders is aracnaphobia, fear of tight spaces is chlaustraphobia, fear of Chuck Norris is called Logic',
'Chuck Norris doesnâ€™t call the wrong number. You answer the wrong phone.',
'There used to be a street named after Chuck Norris, but it was changed because nobody crosses Chuck Norris and lives.',
'Chuck Norris has a grizzly bear carpet in his room. The bear isnâ€™t dead it is just afriad to move.',
'Chuck Norris died 20 years ago, Death just hasnâ€™t built up the courage to tell him yet.',
'If you rate this 5 roundhouse kicks, then Chuck Norris WILL roundhouse kick Justin Bieberâ€™s ass.',
'Chuck Norris has already been to Mars; thatâ€™s why there are no signs of life.',
'Some magicans can walk on water, Chuck Norris can swim through land.',
'Ghosts sit around the campfire and tell Chuck Norris stories.',
'Chuck Norris and Superman once fought each other on a bet. The loser had to start wearing his underwear on the outside of his pants.',
'Chuck Norris can cut through a hot knife with butter',
'Chuck Norris once urinated in a semi truckâ€™s gas tank as a jokeâ€¦.that truck is now known as Optimus Prime.',
'Chuck Norris doesnâ€™t flush the toilet, he scares the sh*t out of it',
'Death once had a near-Chuck Norris experience',
'Chuck Norris counted to infinity â€“ twice.',
'Chuck Norris is the reason why Waldo is hiding.',
'Chuck Norris won American Idol using only sign language',
'Once the cop pulled over Chuck Norrisâ€¦.the cop was lucky to leave with a warning.',
'Chuck Norris can slam a revolving door.',
'Chuck Norris won the World Series of Poker using Pokemon cards',
'When the Boogeyman goes to sleep every night, he checks his closet for Chuck Norris.',
'Chuck Norris will never have a heart attack. His heart isnâ€™t nearly foolish enough to attack him.',
'Chuck Norris can win a game of Connect Four in only three moves.',
'Chuck Norris once kicked a horse in the chin. Its decendants are known today as Giraffes.',
'Chuck Norris once got bit by a rattle snakeâ€¦â€¦.. After three days of pain and agony â€¦â€¦â€¦â€¦â€¦â€¦the rattle snake died',
'There is no theory of evolution. Just a list of animals Chuck Norris allows to live.',
'When Chuck Norris does a pushup, he isnâ€™t lifting himself up, heâ€™s pushing the Earth down.',
'Chuck Norris can light a fire by rubbing two ice-cubes together.',
'Chuck Norrisâ€™ hand is the only hand that can beat a Royal Flush.',
'There is no theory of evolution. Just a list of creatures Chuck Norris has allowed to live.',
'Chuck Norris doesnâ€™t read books. He stares them down until he gets the information he wants.',
'When Chuck Norris throws you into a bottomless pit, you hit the bottom.',
'Chuck Norris doesnâ€™t wear a watch. HE decides what time it is.',
'Chuck Norris does not sleep. He waits.',
'Chuck Norris made a Happy Meal cry.',
'Prisons donâ€™t keep society safe from criminals. Prisons keep criminals safe from Chuck Norris, for now.',
'Outer space exists because itâ€™s afraid to be on the same planet with Chuck Norris.',
'When Chuck Norris was born, the only person crying was the doctor. You NEVER slap Chuck Norris.',
'At the end of WWII, the U.S. Government considered developing 2 weapons: the Atom Bomb, or the Chuck Norris Roundhouse. They made the humane choice.',
'If Chuck Norris were to ever run out of ammo, his weapon would continue to fire out of fear of disappointing Chuck Norris.',
'In 1945 Chuck Norris drank a Redbull and jumped out a plane. For image results, Google the word Hiroshima.',
'Chuck Norris called 911 to order Chinese food and got itâ€¦..',
'Guns are warned not to play with Chuck Norris.',
'Chuck Norris grew a beard at the age of eighteen. Seconds.',
'Chuck Norris runs until the treadmill gets tired',
'Chuck Norris doesnâ€™t mow his lawn, he dares his grass to grow',
'Chuck Norris can give aspirin a headache',
'Montpelier, Vermont is the only state capital without a McDonalds.',
'A cow gives nearly 200,000 glasses of milk in her lifetime.',
'Cuba is the only island in the Caribbean to have a railroad.',
'Earthworms have 5 hearts.',
'People say â€œbless youâ€ when you sneeze because your heart stops for a millisecond.',
'â€œDuffâ€ is the decaying organic matter found on a forest floor.',
'It is impossible to drown and not die. Technically the term â€˜drowningâ€™ refers to the process of taking water into the lungs, not to death caused by that process.',
'Camels have three eyelids to protect themselves from blowing sand.',
'11% of the world is left-handed.',
'The Falkland Isles (pop. about 2000) has over 700000 sheep (350 per person).',
'The average Japanese household watches more than 10 hours of television a day.',
'The Brimstone butterfly (Gonepterix rhamni) has the longest lifetime of the adult butterflies: 9-10 months.',
'A female ferret will die if it goes into heat and cannot find a mate.',
'A full moon is nine times brighter than a half moon.',
'An average human loses about 200 head hairs per day.',
'The average Japanese household watches more than 10 hours of television a day.',
'The Brimstone butterfly (Gonepterix rhamni) has the longest lifetime of the adult butterflies: 9-10 months.',
'A female ferret will die if it goes into heat and cannot find a mate.',
'A full moon is nine times brighter than a half moon.',
'An average human loses about 200 head hairs per day.',
'Dartboards are made out of horse hairs.',
'On average, 2 newborns will be given to the wrong parents every day.',
'In the U.S, Frisbees outsell footballs, baseballs and basketballs combined.',
'The human body is comprised of 80% water.',
'It is believed that Leonardo Da Vinci invented the scissors.',
'Despite a population of over a billion, China has only about 200 family names.',
'Buckingham Palace has 602 rooms.',
'The human heart creates enough pressure when it pumps out to the body to squirt blood 30 feet.',
'Beethoven dipped his head in cold water before he composed.',
'The Olympic was the sister ship of the Titanic, and she provided twenty-five years of service.',
'Your ribs move about 5 million times a year, every time you breathe!',
'Banging your head against a wall uses 150 calories an hour.',
'Starfish have no brains.',
'Children grow faster in the springtime.',
'The national anthem of Greece has 158 verses.',
'During itâ€™s lifetime an oyster changes its sex from male to female and back several times.',
'Cephalacaudal recapitulation is the reason our extremities develop faster than the rest of us.',
'Nutmeg is extremely poisonous if injected intravenously.',
'Daniel Boone hated coonskin caps.',
'More people speak English in China than the United States.',
'Butterflies taste with their hind feet.',
'1 in 5 of the worldâ€™s doctors are Russian.',
'Rape is reported every six minutes in the U.S.',
'Two-thirds of the worldâ€™s eggplant is grown in New Jersey.',
'Olympus Mons is the largest volcano in our solar system.',
'Venus is the only planet that rotates clockwise.',
'In space you cannot cry because there is no gravity to make the tears flow.',
'Elephants have the longest pregnancy in the animal kingdom at 22 months. The longest human pregnancy on record is 17 months, 11 days.',
'California consumes more bottled water than any other product.',
'In 1936, American track star Jesse Owens beat a race horse over a 100-yard course. The horse was given a head start.',
'A large flawless emerald is worth more than a similarly large flawless diamond.',
'Cherâ€™s last name was â€œSarkissian.â€ She changed it because no one could pronounce it.',
'Mexican free-tailed bats sometimes fly up to two miles high to feed or to catch tail-winds that carry them over long distances at speeds of more than 60 miles per hour.',
'A man will ejaculate approximately 18 quarts of semen in his lifetime.',
'It is estimated that millions of trees are planted by forgetful squirrels.',
'In â€œSilence of the Lambsâ€, Hannibal Lector (Anthony Hopkins) never blinks.',
'In Kentucky, it is illegal to carry ice-cream in your back pocket.',
'A cat uses its whiskers to determine if a space is too small to squeeze through.',
'A cesium atom in an atomic clock beats 9,192,631,770 times a second.',
'A group of crows is called a murder.',
'At latitude 60 degrees south you can sail all the way around the world.',
'The zorilla is the smelliest animal on the planet. Itâ€™s anal glands can be smelled from half a mile away.',
'The first bomb the Allies dropped on Berlin in WWII killed the only elephant in the Berlin Zoo.',
'A dragonfly has a lifespan of 24 hours.',
'99% of the solar system mass is concentrated in the sun.',
'Ketchup was sold in the 1830s as medicine.',
'Degringolade means to fall and disintegrate.',
'The Amazon is the worldâ€™s largest river, 3,890 miles (6,259 km) long.',
'Grapes explode when you put them in the microwave.',
'A pound of houseflies contains more protein than a pound of beef',
'A donkey will sink in quicksand but a mule wonâ€™t.',
'Nepal is the only country that doesnâ€™t have a rectangular flag.',
'Nerve impulses to and from the brain travel as fast as 170 miles (274 km) per hour.',
'â€œLassieâ€ was played by a group of male dogs; the main one was named Pal.',
'In May 1948, Mt Ruapehu and Mt Ngauruhoe, both in New Zealand, erupted simultaneously.',
'A rhinoceros horn is made of compacted hair.',
'The international telephone dialing code for Antarctica is 672.',
'Itâ€™s illegal to spit on the sidewalk in Norfolk, Virginia.',
'In the four professional major north american sports (baseball, basketball, football and hockey) only 7 teams have nicknames that do not end with an s.',
'A lion in the wild usually makes no more than 20 kills a year.',
'Woodpecker scalps, porpoise teeth, and giraffe tails have all been used as money.',
'Shakespeare invented the words â€œassassinationâ€ and â€œbump.â€',
'There is no solid proof of who built the Taj Mahal.',
'Australian Rules football was originally designed to give cricketers something to play during the off season.',
'The male seahorse carries the eggs until they hatch instead of the female.',
'Ignoramus: The grand jury used to write ignoramus on the back of indictments not found or not to be sent to court. This was often constructed as an indication of the stupidity of the jury, hence its present meaning.',
'Camels chew in a figure 8 pattern.',
'India has a Bill of Rights for cows.',
'Jackals have one more pair of chromosomes than dogs or wolves.',
'Dartboards are made out of horse hairs.',
'The average life of a taste bud is 10 days.',
'In 1980, a Las Vegas hospital suspended workers for betting on when patients would die.',
'Dibble means to drink like a duck.',
'It was once against the law to have a pet dog in a city in Iceland.',
'A B-25 bomber crashed into the 79th floor of the Empire State Building on July 28, 1945.',
'A giraffe can clean its ears with its 21-inch tongue!',
'In France, thereâ€™s a place called Y.',
'One in every 4 Americans has appeared on television at least once in their life.',
'In ancient Rome, when a man testified in court he would swear on his testicles.',
'The average human will shed 40 pounds of skin in a lifetime.',
'A Virginia law requires all bathtubs to be kept inside the house',
'Truck driving is the most dangerous occupation by accidental deaths (799 in 2001).',
'A group of toads is called a knot.',
'At any given time, there are at least 1,800 thunderstorms in progress over the earthâ€™s atmosphere.',
'The top butterfly flight speed is 12 miles per hour. Some moths can fly 25 miles per hour!',
'More than 30% of the people in the world have never made or received a telephone call.',
'Termites have been known to eat food twice as fast when heavy metal music is playing.',
'All female bees in a given hive are sisters.',
'Owls are the only birds that can see the color blue.',
'The Automated Teller Machine (ATM) was introduced in England in 1965.',
'Cats have over 100 vocal sounds; dogs only have 10.',
'It was discovered on a space mission that a frog can throw up.',
'Mailing an entire building has been illegal in the U.S. since 1916 when a man mailed a 40,000-ton brick house across Utah to avoid high freight rates.',
'A shark is the only fish that can blink with both eyes.',
'Johnny Appleseed planted apples so that people could use apple cider to make alcohol.',
'City with the most Roll Royces per capita: Hong Kong.',
'The past-tense of the English word â€œdareâ€ is â€œdurstâ€',
'Almonds are a member of the peach family.',
'Humans use a total of 72 different muscles in speech.',
'Baby robins eat 14 feet of earthworms every day',
'The most powerful earthquake to strike the United States occurred in 1811 in New Madrid, Missouri. The quake shook more than one million square miles, and was felt as far as 1,000 miles away.',
'In every episode of Seinfeld there is a Superman somewhere.',
'Babies are born without knee caps. They donâ€™t appear until the child reaches 2-6 years of age.',
'The Bible, the worldâ€™s best-selling book, is also the worldâ€™s most shoplifted book.',
'More than 1,000 different languages are spoken on the continent of Africa.',
'It is forbidden for aircraft to fly over the Taj Mahal.',
'Any free moving liquid in outer space will form itself into a sphere because of its surface tension.',
'â€œCanadaâ€ is an Indian word meaning â€œBig Villageâ€.',
'In 1984, a Canadian farmer began renting advertising space on his cows.',
'Bees have 5 eyes. There are 3 small eyes on the top of a beeâ€™s head and 2 larger ones in front.',
'Certain frogs can be frozen solid then thawed, and continue living.',
'55.1% of all US prisoners are in prison for drug offenses.',
'Hawaii is the only coffee producing state.',
'The first McDonaldâ€™s restaurant in Canada was in Richmond, British Columbia.',
'Albert Einstein and Charles Darwin both married their first cousins',
'Half of all bank robberies take place on a Friday.',
'Sharon Stone was the first Star Search spokes model.',
'Elvis had a twin brother named Garon, who died at birth, which is why Elvis middle name was Aron.',
'In 1980, a Las Vegas hospital suspended workers for betting on when patients would die.',
'Dr. Seuss pronounced his name â€œsoyceâ€.',
'Our eyes are always the same size from birth, but our nose and ears never stop growing.',
'In Utah, it is illegal to swear in front of a dead person.',
'Due to precipitation, for a few weeks, K2 is taller than Mt. Everest.',
'A scholar who studies the Marquis de Sade is called a Sadian not a Sadist.',
'What is called a â€œFrench kissâ€ in the English speaking world is known as an â€œEnglish kissâ€ in France.',
'Insects outnumber humans 100,000,000 to one.',
'Table tennis balls have been known to travel off the paddle at speeds up to 160 km/hr.',
'Experts at Intel say that micro processor speed will double every 18 months for at least the next 10 years.',
'The giant squid has the largest eyes in the world.',
'Your tongue is the only muscle in your body that is attached at only one end.',
'A duckâ€™s quack doesnâ€™t echo, and no one knows why.',
'Elwood Edwards did the voice for the AOL sound files (i.e. â€œYouâ€™ve got Mail!â€).',
'Americans are responsible for about 1/5 of the worldâ€™s garbage annually.',
'Lizards can self-amputate their tails for protection. It grows back after a few months.',
'The most frequently named bugs from the Bible are: Locust: 24, Moth: 11, Grasshopper: 10, Scorpion: 10, Caterpillar: 9, and Bee: 4.',
'Dr. Seuss pronounced his name so that it would rhyme with rejoice.',
'The thyroid cartilage is more commonly known as the adams apple.',
'If you travel across Russia, you will cross seven time zones.',
'If you feed a seagull Alka-Seltzer, its stomach will explode.',
'The people of France eat more cheese than any other country in the world.',
'Camels have three eyelids to protect themselves from blowing sand.',
'In Baltimore USA it is illegal to wash or scrub a sink regardless of how dirty it is.',
'Sherlock Holmes NEVER said â€œElementary, my dear Watsonâ€',
'In 1949, forecasting the relentless march of science, Popular Mechanics said computers in the future may weigh no more than 5 tons.',
'There is a city called Rome on every continent.',
'Donkeys kill more people than plane crashes.',
'It takes 12,000 head of cattle to produce one pound of adrenaline.',
'In Bangladesh, kids as young as 15 can be jailed for cheating on their finals.',
'A crocodile cannot stick its tongue out.',
'Blondes have more hair than dark-haired people do.',
'Honey does not spoil.',
'Adult elephants canâ€™t jump.',
'Jet lag was once called boat lag, before there were jets.',
'There are about 450 types of cheese in the world. 240 come from France.',
'The number â€œfourâ€ is considered unlucky in Japan because it is pronounced the same as â€œdeathâ€.',
'The electric chair was invented by a dentist.',
'England is smaller than New England.',
'Itâ€™s impossible to sneeze with your eyes open.',
'Switzerland is the only country with a square flag.',
'In 10 minutes, a hurricane releases more energy than all the worldâ€™s nuclear weapons combined.',
'Ancient Egyptians shaved off their eyebrows to mourn the deaths of their cats.',
'Illinois has the highest number of personalized license plates than any other state.',
'The average American/Canadian will eat about 11.9 pounds of cereal per year!',
'There are about a million ants per person. Ants are very social animals and will live in colonies that can contain almost 500,000 ants.',
'More than 90% of the Nicaraguan people are Roman Catholic.',
'Los Angelesâ€™ full name is â€œEl Pueblo de Nuestra Senora la Reina de los Angeles de Porciunculaâ€.',
'A necropsy is an autopsy on animals.',
'Rugby, North Dakota is the geographical center of North America.',
'A hydrodaktulpsychicharmonica is a variety of musical glasses.',
'Karoke means empty orchestra in Japanese.',
'Although modern images of India often show poverty and lack of development, India was the richest country on earth until the time of British invasion in the early 17th Century.',
'The U.S. Post Office handles 43 percent of the worldâ€™s mail.',
'A lightning bolt generates temperatures five times hotter than those found on the sunâ€™s surface.',
'There is actually no danger in swimming right after you eat, though it may feel uncomfortable.',
'In the Scottish Hebrides, an island is defined as being an island only if it is big enough to sustain 1 sheep.',
'The Hawaiian alphabet has only 12 letters.',
'Someone paid $14,000 for the bra worn by Marilyn Monroe in the film â€˜Some Like It Hotâ€™.',
'A fierce gust of wind blew 45 year old Vittorio Luiseâ€™s car into a rover near Naples, Italy, in 1980. He managed to break a window, climb out and swim to shoreâ€“where a tree blew over and killed him.',
'There are approximately 100 million acts of sexual intercourse each day.',
'Entomophobia is the fear of insects.',
'Every US president has worn glasses (just not always in public).',
'A female ferret will die if it goes into heat and cannot find a mate.',
'Hair is made from the same substance as fingernails.',
'The Nullarbor Plain of Australia covers 100,000 square miles (160,900 km) without a tree.',
'Salt Lake City has a law against carrying an unwrapped ukulele on the street.',
'A snail can have 25,000 teeth.',
'No matter where you stand in Michigan, you are never more than 85 miles from a Great Lake.',
'Rudyard Kipling, living in Vermont in the 1890s invented the game of snow golf. He would paint his golf balls red so that they could be located in the snow.',
'You can lead a cow upstairs but not downstairs.',
'It is physically impossible for pigs to look up in the sky.',
'A healthy (non-colorblind) human eye can distinguish between 500 shades of gray.',
'A syzygy occurs when three atronomical bodies line up.',
'Shakespeare invented the word â€œassassinationâ€ and â€œbump.â€',
'Your heart beats over 100,000 times a day!',
'The Beetham Tower has 47 floors.',
'There are 293 ways to make change for a dollar.',
'All polar bears are left-handed.',
'George Washington is the only man whose birthday is a legal holiday in every state of the U.S as of a few years ago.',
'Catsâ€™ urine glows under a black light.',
'For every 230 cars that are made, 1 will be stolen.',
'Dr. Seuss coined the word nerd in his 1950 book â€œIf I Ran The Zoo.â€',
'A word or sentence that is the same front and back (racecar, kayak) is called a â€œpalindromeâ€.',
'Abraham Lincolnâ€™s ghost is said to haunt the White House.',
'Greenland is the largest island in the world.',
'The Guinness Book of Records holds the record for being the book most often stolen from Libraries.',
'One in eight million people has progeria, a disease that causes people to grow faster than they age.',
'An average human scalp has 100,000 hairs.',
'A lionâ€™s roar can be heard from five miles away.',
'There are more types of insects in one tropical rain forest tree than there are in the entire state of Vermont.',
'Cats have over one hundred vocal sounds; dogs only have about ten.',
'Adolf Hitler was a vegetarian, and had only ONE testicle.',
'The pancreas produces Insulin.',
'Americans on the average eat 18 acres of pizza every day.',
'Relative to size, the strongest muscle in the body is the tongue.',
'Your stomach has to produce a new layer of mucus every two weeks or it will digest itself.',
'A two-bit moon is in its first quarter.',
'Dreamt is the only English word that ends in the letters amt',
'Pepsi originally contained pepsin, thus the name.',
'Bulgarians are known to be the biggest yogurt eaters in the world.',
'0.3% of all road accidents in Canada involve a Moose.',
'Maine is the only state that has borders with only one other state.',
'Male bats have the highest rate of homosexuality of any mammal.',
'The surface of the human skin is 6.5 square feet (2m).',
'The largest taxi fleet in the world is found in Mexico City. The city boasts a fleet of over 60,000 taxis.',
'Britainâ€™s shortest river is the Brun which runs through Burnley in Lancashire.',
'Giraffes and rats can last longer without water than camels.',
'More people are killed each year from bees than from snakes.',
'Disneyland opened in 1955.',
'Bacteria, the tiniest free-living cells, are so small that a single drop of liquid contains as many as 50 million of them.',
'Corduroy comes from the French, cord du roi or cloth of the king.',
'It is illegal to frown at cows in Bladworth, Saskatchewan.',
'There were 240 pedestrian fatalities in New York City in 1994.',
'In Japan, watermelons are squared. Itâ€™s easier to stack them that way.',
'Bird droppings are chief export of Nauru, an island nation in the Western Pacific.',
'Common Cobra venom is not on the list of top 10 venoms yet it is still 40 times more toxic than cyanide.',
'A species of earthworm in Australia grows up to 10 feet in length.',
'An ostrichâ€™s eye is bigger than its brain.',
'A female swine, or a sow, will always have a even number of teats or nipples, usually twelve.',
'It takes 8.5 minutes for light to get from the sun to earth.',
'Lightning strikes the earth about 8 million times a day.',
'Contrary to popular belief, suicide rates during the Christmas holiday are low. The highest rates are during the spring.',
'Christmas trees have been sold in the U.S. since 1850.',
'Norwegian scientists have hypothesized that Rudolphâ€™s red nose is probably the result of a parasitic infection of his respiratory system.',
'Christmas trees usually grow for about 15 years before they are sold.',
'Alabama was the first state in the United States to officially recognize Christmas in 1836.',
'The country code for Russia is â€œ007?.',
'Angel Falls in Venezuela is the worldâ€™s highest waterfall, at 3,212 feet (979 m).',
'A crocodiles tongue is attached to the roof of its mouth.',
'Great Britain was the first county to issue postage stamps. Hence, the postage stamps of Britain are the only stamps in the world not to bear the name of the country of origin. However, every stamp carries a relief image or a silhouette of the monarchâ€™s head instead.',
'Your stomach needs to produce a new layer of mucus every two weeks or it would digest itself.',
'Most dust particles in your house are made from dead skin!',
'There are 1,792 steps in the Eiffel Tower',
'Koalas never drink water. They get fluids from the eucalyptus leaves they eat.',
'Arabic numerals are not really Arabic; they were created in India.',
'EMI stands for â€˜ Electrical and Musical Instrumentsâ€™.',
'Elephants only sleep for two hours each day.',
'In space, astronauts cannot cry, because there is no gravity, so the tears canâ€™t flow.',
'Hara kiri is an impolite way of saying the Japanese word seppuku which means, literally, belly splitting.',
'An Olympic gold medal must contain 92.5 percent silver',
'There are 240 dots on an arcade Pac-Man game',
'Every time you lick a stamp you consume 1/10 of a calorie.',
'The first female guest host of â€œSaturday Night Liveâ€ was Candace Bergen.',
'A manâ€™s beard grows fastest when he anticipates sex.',
'King Louis XIX ruled France for 15 minutes.',
'Because of the rotation of the earth, an object can be thrown farther if it is thrown west.',
'If a frogâ€™s mouth is held open for too long the frog will suffocate.',
'A duck has three eyelids.',
'In most watch advertisements the time displayed on a watch is 10:10.',
'An American urologist bought Napoleonâ€™s penis for $40,000.',
'Antarctica is the only continent that does not have land areas below sea level.',
'Jimmy Carter was the first U.S. President to be born in a hospital.',
'Facetious and abstemious contain all the vowels in the correct order, as does arsenious, meaning containing arsenic.',
'160 cars can drive side by side on the Monumental Axis in Brazil, the worldâ€™s widest road.',
'Mongolia is the largest landlocked country.',
'Maine is the only state (in USA) whose name is just one syllable.',
'Carnivorous animals will not eat another animal that has been hit by a lightning strike.',
'Mr. Rogers was an ordained minister.',
'In 1825, Upper Peru became Bolivia.',
'The highest point in Pennsylvania is lower than the lowest point in Colorado.',
'The Michelin man is known as Mr. Bib. His name was Bibendum in the companyâ€™s first ads in 1896.',
'Gabriel, Michael, and Lucifer are the only angels named in the Bible.',
'Youâ€™re born with 300 bones, but by the time you become an adult, you only have 206.',
'Jamaica has the most churches per square mile than any other country in the world.',
'In 1859, 24 rabbits were released in Austrailia. Within six years the population grew to 2 million.',
'When the Titanic sank, 2228 people were on it. Only 706 survived.',
'The electric chair was invented by a dentist.',
'The plastic things on the end of shoelaces are called aglets.',
'A hippo can open its mouth wide enough to fit a four foot tall child inside.',
'Butterflies cannot fly if their body temperature is less than 86 degrees.',
'Clouds fly higher during the day than the night.',
'Between 1902 and 1907 the same tiger killed 436 people in India.',
'Many butterflies can taste with their feet to find out whether the leaf they sit on is good to lay eggs on to be their caterpillarsâ€™ food or not.',
'The human brain is about 75% water.',
'A group of kangaroos is called a mob.',
'Ever wonder where the term Work Smarterâ€¦Not Harder originated? Allan F. Mogensen, the creator of Work Simplification, coined the phrase in the 1930s. The 1990s equivalent term is probably Business Process Reengineering.',
'A woodchuck breathes only 10 times in hibernation.',
'The Declaration of Independence was written on hemp (marijuana) paper.',
'The longest one-syllable word in the English language is â€œscreeched.â€',
'Michigan was the first state to have roadside picnic tables.',
'$283,200 is the absolute highest amount of money you can win on Jeopardy.',
'Most lipstick contains fish scales.',
'Possums have one of the shortest pregnancies at 16 days. The shortest human pregnancy to produce a healthy baby was 22 weeks, 6 days â€” the baby was the length of a ballpoint pen.',
'Frog-eating bats identify edible from poisonous frogs by listening to the mating calls of male frogs. Frogs counter by hiding and using short, difficult to locate calls.',
'Broccoli and cauliflower are the only vegetables that are flowers.',
'A Boeing 747s wingspan is longer than the Wright brotherâ€™s first flight.',
'Dogs and cats consume over $11 billion worth of pet food a year',
'Thirty-five percent of the people who use personal ads for dating are already married.',
'Jim Morrison, of the 60s rock group The Doors, was the first rock star to be arrested on stage.',
'You share your birthday with at least 9 million other people in the world.',
'In a tradition dating to the begining of the Westminster system of government, the bench in the middle of a Westminster parliarment is two and a half sword lengths long. This was so the government and oppositon couldnâ€™t have a go at each other if it all got a bit heated',
'If you attempted to count the stars in a galaxy at a rate of one every second it would take around 3,000 years to count them all.',
'In England, the Speaker of the House is not allowed to speak.',
'In the last 4000 years no new animals have been domesticated.',
'Hannibal had only one eye after getting a disease while attacking Rome.',
'An ostrichâ€™s eye is bigger than its brain.',
'The human heart creates enough pressure in the bloodstream to squirt blood 30 feet.',
'In Italy, 17 is considered an unlucky number. In Japan, 4 is considered an unlucky number.',
'The worldâ€™s longest snake (by reliable documentation) is the reticulated python, with a maximum length of, perhaps, 30 feet.',
'Ramses brand condom is named after the great pharaoh Ramses II who fathered over 160 children.',
'In the United States, more Frisbee discs are sold each year than baseballs, basketballs, and footballs combined.',
'A chameleonâ€™s tongue is twice the length of its body.',
'In Alaska it is illegal to shoot at a moose from the window of an airplane or other flying vehicle.',
'The average garden variety caterpillar has 248 muscles in its head.',
'Anise is the scent on the artificial rabbit that is used in greyhound races.',
'Ernest Vincent Wright wrote a 50,000 word novel without any word containing â€œe.â€',
'The average personâ€™s left hand does 56% of the typing.',
'At the height of its power in 400 BC, the Greek city of Sparta had 25,000 citizens and 500,000 slaves.',
'It is believed that Shakespeare was 46 around the time that the King James Version of the Bible was written. In Psalms 46, the 46th word from the first word is shake and the 46th word from the last word is spear.',
'The cruise liner Queen Elizabeth II moves only six inches for each gallon of diesel that it burns.',
'Wearing headphones for just an hour will increase the bacteria in your ear by 700 times.',
'Itâ€™s estimated that at any one time around 0.7% of the worldâ€™s population is drunk.',
'Like fingerprints, everyoneâ€™s tongue print is different!',
'Everyday, more money is printed for Monopoly sets than for the U.S. Treasury.',
'There is a hotel in Sweden built entirely out of ice; it is rebuilt every year.',
'Intelligent people have more zinc and copper in their hair.',
'Because metal was scarce, the Oscars given out during World War II were made of wood.',
'One in fourteen women in America is a natural blonde. Only one in sixteen men is.',
'The venom of the Australian Brown Snake is so powerful only 1/14,000th of an ounce is enough to kill a human.',
'Ballroom dancing is a major at Brigham University.',
'The human feet perspire half a pint of fluid a day',
'In every episode of â€œSeinfeldâ€ there is a Superman picture or reference somewhere.',
'There is a city in Norway called â€œHellâ€',
'A standard grave is 7â€™8 x 3â€™2 x 6.',
'Tina Turnerâ€™s real name is Annie Mae Bullock.',
'Babies are born without knee caps. They donâ€™t appear until the child reaches 2-6 years of age.',
'You is the second most spoken English word',
'The first novel ever written on a typewriter is Tom Sawyer.',
'Charlie Chaplin once won third prize in a Charlie Chaplin look-alike contest.',
'According to Genesis 1:20-22, the chicken came before the egg.',
'Arachibutyrophobia is the fear of peanut butter sticking to the roof of your mouth.',
'If you put a drop of liquor on a scorpion, it will instantly go mad and sting itself to death.',
'The average human blinks their eyes 6,205,000 times each year.',
'US Dollar bills are made out of cotton and linen.',
'The glue on Israeli postage is certified kosher.',
'98% of all murders and rapes are by a close family member or friend of the victim.',
'The February of 1865 is the only month in recorded history not to have a full moon.',
'Some people say that when the black bands on the Woolybear caterpillar are wide, a cold winter is coming.',
'There are more donut shops in Canada per capita than any other country.',
'Termites outweigh humans by almost ten to one.',
'John Adams, Thomas Jefferson, and James Monroe died on July 4th.',
'Construction workers hard hats were first invented and used in the building of the Hoover Dam in 1933.',
'Groaking is to watch people eating in hopes that they will offer you some.',
'Right handed people live, on average, nine years longer than left handed people do.',
'It can take as long as 4 hours to hard-boil an ostrich egg.',
'14% of all facts and statistics are made up and 27% of people know that fact.',
'The volume of the earthâ€™s moon is the same as the volume of the Pacific Ocean.',
'The cheetah is the only cat that canâ€™t retract its claws.',
'A rat can last longer without water than a camel.',
'A jumbo jet uses 4,000 gallons of fuel to take off.',
'In the Philippines, MABUHAY means Hello.',
'Each year there is one ton of cement poured for each man, woman and child in the world.',
'An ant always falls over on its right side when intoxicated.',
'The most common name in Italy is Mario Rossi.',
'It is impossible to lick your elbow.',
'Sailfish can leap out of the water and into the air at a speed of 50 miles (81 km) per hour.',
'A â€œ2 by 4? is really 1 1/2 by 3 1/2.',
'If you look carefully at the picture of Mona Lisa, you will notice a bridge in the background.',
'The only real person to be a PEZ head was Betsy Ross.',
'Each year there is one ton of cement poured for each man woman and child in the world.',
'Chinese Crested dogs can get acne.',
'February 1865 is the only month in recorded history not have a full moon.',
'40% of all people who come to a party in your home snoop in your medicine cabinet',
'It is illegal to hunt camels in the state of Arizona.',
'Giant flying foxes that live in Indonesia have wingspans of nearly six feet.',
'The first CD pressed in the US was Bruce Springsteenâ€™s â€œBorn in the USAâ€.',
'Eagles can live in captivity for up to 46 years.',
'People photocopying their buttocks are the cause of 23% of all photocopier faults worldwide.',
'When sharks take a bite, their eyes roll back and their teeth jut out.',
'Your stomach produces a new layer of mucus every two weeks so that it doesnâ€™t digest itself.',
'More people are allergic to cowâ€™s milk than any other food.',
'The â€œspotâ€ on the 7-Up logo comes from its inventor who had red eyes. He was an albino.',
'The average human brain has about 100 billion nerve cells.',
'There are more beetles than any other animal. In fact, one out of every four animals is a beetle.',
'15 million blood cells are destroyed in the human body every second.',
'A coward was originally a boy who took care of cows.',
'The San Francisco Cable cars are the only mobile National Monuments',
'Peanuts are one of the ingredients of dynamite.',
'Only female mosquitoes bite.',
'Devon is the only county in Great Britain to have two coasts.',
'A group of finches is called a Charm.',
'During the chariot scene in â€œBen Hur,â€ a small red car can be seen in the distance.',
'The angel falls in Venezuela are nearly 20 times taller than Niagara Falls.',
'In 1961, MIT student Steve Russell, created SPACEWARS, the first interactive computer game, on a Digital PDP-1 (Programmed Data Processor-1) mainframe computer. Limited by the computer technology of the time, ASCII text characters were the â€˜graphicsâ€™ and people could only play the game on a device that took up the floorspace of a small house.',
'In the great fire of London in 1666 half of London was burnt down but only 6 people were injured.',
'An enneahedron is solid with nine faces.',
'Hedenophobic means fear of pleasure.',
'For much of the way, the Lewis and Clark expedition was led by a woman, Sacagawea, a Shoshone Indian. Thatâ€™s where that saying came fromâ€¦ Behind every successful man, there is a woman with a road map.',
'There are no words in the dictionary that rhyme with orange, purple, silver and month.',
'A man named Charles Osborne had the hiccups for 69 years!',
'They NEVER said â€œBeam me up, Scottyâ€ on Star Trek.',
'The hammerthrow is illegal as a high school sport in all states except Rhode Island.',
'Coca-Cola would be green if coloring werenâ€™t added to it.',
'If you toss a penny 10,000 times it will not be heads 5000 times but more like 4950. The head picture weighs more, so it ends up on the bottom.',
'Canadian researchers have found that Einsteinâ€™s brain was 15% wider than normal.',
'Humphrey Bogart NEVER said â€œPlay it again, Samâ€ in Casablanca',
'All Hebrew originating names that end with the letters el have something to do with God.',
'A single sheeps fleece might well contain as many as 26 million fibres.',
'Ham radio operators got the term ham coined from the expression ham-fisted operators a term used to describe early radio users who sent Morse code (i.e pounded their fists).',
'Columbia University is the second largest landowner in New York City, after the Catholic Church.',
'Because metal was scarce, the Oscars given out during World War II were made of wood.',
'The bonobo monkeys use sex (and/or sexual favors) to placate members of their social group instead of grooming. They are one of the few species of animals (humans being another) that have sex out of season and for fun.',
'Only one in two billion people will live to be 116 or older.',
'It is illegal to eat oranges while bathing in California.',
'Ethernet is a registered trademark of Xerox, Unix is a registered trademark of AT&T.',
'French speaking residents of Belgium are called Walloons.',
'The average shelf-life of a latex condom is about two years.',
'An estimated 80% of animals on Earth have six legs.',
'Because of the salt content of the Dead Sea, it is difficult to dive below its surface.',
'In most advertisements, including newspapers, the time displayed on a watch is 10:10.',
'All snow crystals are hexagonal.',
'Bats always turn left when exiting a cave.',
'If you yelled for 8 years, 7 months and six days, you would have produced enough sound energy to heat one cup of coffee.',
'Average life span of a major league baseball: 7 pitches.',
'Coca-Cola contained Coca (whose active ingredient is cocaine) from 1885 to 1903.',
'The U.S. bought Alaska for 2 cents an acre from Russia.',
'When you sneeze, all your bodily functions stop even your heart.',
'There are over a million described species of insects. Some people estimate there are actually between 15 and 30 million species.',
'The females of some moth species lack wings, all they can do to move is crawl.',
'Scotland has more redheads than any other part of the world.',
'Caterpillars have about four thousand muscles. Humans, by comparison, have only about six hundred.',
'People eat insects â€“ called â€œEntomophagyâ€(people eating bugs) â€“ it has been practiced for centuries throughout Africa, Australia, Asia, the Middle East, and North, Central and South America. Why? Because many bugs are both protein-rich and good sources of vitamins, minerals and fats.',
'The US has more personal computers than the next 7 countries combined.',
'Go. is the shortest complete sentence in the English language.',
'The first streetlights in America were installed in Philadelphia around 1757.',
'Charlie Chaplin once won third prize in a Charlie Chaplin look-alike contest.',
'Carolyn Shoemaker has discovered 32 comets and approximately 300 asteroids.',
'Hippopotamuses do eighty percent of their vocalization under water.',
'The odds of being born male are about 51.2%, according to census.',
'Nepal is the only country that has a non-rectangular flag. It is also asymmetrical.',
'Every year, Mexico City sinks about 10 inches.',
'At the nearest point, Russia and America are less than 4 km apart.',
'Flamingos can only eat with their heads upside down.',
'A rainbow can only occur when the sun is 40 degrees or less above the horizon.',
'It takes one fifteen-to-twenty-year-old tree to produce seven hundred paper grocery bags.',
'Humans and dolphins are the only species that have sex for pleasure.',
'Rhythm is the longest English word without a vowel.',
'A group of frogs is called an army.',
'A square mile of fertile earth has 32,000,000 earthworms in it.',
'Impotence is legal grounds for divorce in 24 American states.',
'A snake has no ears. But its tongue is extremely sensitive to sound vibrations. By flicking its tongue, a snake can pick up sound waves-so a snake â€˜hears with his tongueâ€¦sort of!',
'If you come from Manchester, you are a Mancunian.',
'Dragonflies are capable of flying sixty miles per hour, making them one of the fastest insects. This is good since they are in a big hurry, as they only live about twenty-four hours.',
'In Italy, it is illegal to make coffins out of anything except nutshells or wood.',
'Elephants are the only mammals that cannot jump.',
'Anne Boleyn, Queen Elizabeth Iâ€™s mother, had six fingers on one hand.',
'In England, the Speaker of the House is not allowed to speak.',
'A group of rhinos are called a crash.',
'Proportional to their size, cats have the largest eyes of all mammals.',
'Catâ€™s urine glows under a blacklight.',
'A wind with a speed of 74 miles or more is designated a hurricane.',
'Peter Falk, who played â€œColumbo,â€ has a glass eye.',
'Right handed people live, on average, nine years longer than left-handed people',
'Certain fireflies emit a light so penetrating that it can pass through flesh and wood.',
'One quarter of the bones in your body, are in your feet!',
'A forfeited game in baseball is recorded as a 9-0 score. In football it is recorded as a 1-0 score.',
'A cubic mile of fog is made up of less than a gallon of water.',
'Beetles taste like apples, wasps like pine nuts, and worms like fried bacon.',
'At birth a panda is smaller than a mouse and weighs about four ounces.',
'In 1990, Engineers digging a railway tunnel under the English Channel broke through the last dividing rock and joined Britain to mainland Europe for the first time since the Ice Age.',
'Butte County, South Dakota is the geographical center of the U.S.',
'Anteaters prefer termites to ants.',
'A squirrel cannot contract or carry the rabies virus.',
'A Czech man, Jan Honza Zampa, holds the record for drinking one liter of beer in 4.11 seconds.',
'If you plant an apple seed, it is almost guaranteed to grow a tree of a different type of apple.',
'Chinese Crested dogs can get acne.',
'In English, four is the only digit that has the same number of letters as its value.',
'Buckingham Palace in England has over six hundred rooms.',
'In the average lifetime, a person will walk the equivalent of 5 times around the equator.',
'There are about 24,000 species of butterflies. The moths are even more numerous: about 140,000 species of them were counted all over the world.',
'Approximately 98% of software in China is pirated.',
'No word in the English language rhymes with month, orange, silver, or purple.',
'Some moths never eat anything as adults because they donâ€™t have mouths. They must live on the energy they stored as caterpillars.',
'By raising your legs slowly and lying on your back, you cannot sink into quicksand.',
'Georgiaâ€™s state motto is â€œWisdom, Justice and Moderation.â€',
'The Chuck E. Cheese franchise was created by Atari, a resteraunt combining robotic animals and arcade games with family meals. They name the franchise a Pizza Time Theater. Chuck E. Cheese was first opened in 1977.',
'14% of Americans have skinny-dipped with a member of the opposite sex at least once.',
'There is a city called Rome on every continent.',
'Because of heavy traffic congestion, Julius Caesar banned all wheeled vehicles from Rome during daylight hours.',
'If you bring a raccoonâ€™s head to the Henniker, New Hampshire town hall, you are entitled to receive $.10 from the town.',
'By raising your legs slowly and lying on your back, you cannot sink into quicksand.',
'Dueling is legal in Paraguay as long as both parties are registered blood donors.',
'The catfish has over 27000 taste buds (more than any other animal)',
'When we think of Big Ben in London, we think of the clock. Actually, itâ€™s the bell.',
'Right handed people live, on average, nine years longer than left handed people do.',
'President John F Kennedy could read 4 newspapers in 20 minutes.',
'Cyprus has a map on its flag.',
'All of the clocks in the movie â€œPulp Fictionâ€ are stuck on 4:20.',
'Negative emotions such as anxiety and depression can weaken your immune system.',
'The toothbrush was invented in China in 1498.',
'A snail can sleep for 3 years.',
'It takes the insect-eating Venus Flytrap plant only half a second to shut its trap on its prey.',
'Ghosts appear in 4 Shakespearian plays; Julius Caesar, Richard III, Hamlet and Macbeth.',
'Mice, whales, elephants, giraffes and man all have seven neck vertebra.',
'Iron nails cannot be used in aok because the acid in the wood corrodes them.',
'Goethe couldnâ€™t stand the sound of barking dogs and could only write if he had an apple rotting in the drawer of his desk.',
'Dominica, Mexico, Zambia, Kiribati, Fiji and Egypt all have birds on their flags.',
'Bamboo (the worldâ€™s tallest grass) can grow up to 90 cm in a day.',
'All the dirt from the foundation to build the World Trade Center in NYC was dumped into the Hudson River to form the community now known as Battery City Park.',
'A group of geese on the ground is called a gaggle, a group of geese in the air is a skein.',
'A snail can sleep for three years.',
'On average, 12 newborns will be given to the wrong parents daily.',
'Ninety percent of New York City cabbies are recently arrived immigrants.',
'Vatican City is the smallest country in the world, with a population of 1000 and just 108.7 acres.',
'There are 45 miles of nerves in the skin of a human being.',
'The average child recognizes over 200 company logos by the time he enters first grade.',
'There are over 58 million dogs in the US',
'Chameleons can move their eyes in two directions at the same time.',
'Rubber bands last longer when refrigerated.',
'Did you know you share a birthday with at least nine other million people in the world?',
'About 55% of all movies are rated R.',
'If you were to take a taxicab from New York City to Los Angeles, it would cost you $8,325.',
'A poem written to celebrate a wedding is called a epithalamium.',
'Australian soldiers used the song â€œWeâ€™re Off to See the Wizardâ€ as a marching song in WWII.',
'Four men in the history of boxing have been knocked out in the first eleven seconds of the first round.',
'Happy as a clam is from the expression happy as a clam at high tide. Clams are only harvested when the tide is out.',
'All totalled, the sunlight that strikes Earth at any given moment weighs as much as an ocean liner.',
'A snail takes 33 hours to crawl one mile.',
'A rhinocerosâ€™ horn is made of compacted hair.',
'A shrimpâ€™s heart is in its head.',
'A skunkâ€™s smell can be detected by a human a mile away.',
'The most sensitive cluster of nerves is at the base of the spine.',
'The surface of the Earth is about 60% water and 10% ice.',
'More people are afraid of spiders than death. Amazingly, few people are afraid of Champagne corks even though you are more likely to be killed by one than by a spider.',
'â€Judge Judyâ€ has a $25,000,000 salary, while Supreme Court Justice Ginsberg has a $190,100 salary.',
'The ZIP in â€œZIP codeâ€ means Zoning Improvement Plan.',
'Gary, Indiana is the murder capital of the U.S. â€“ probably the world.',
'Amphibious is based upon Greek words that mean living a double life and amphibians live in both land and water.',
'In Miami, Florida, roosting vultures have taken to snatching poodles from rooftop patios.',
'Coconuts kill about 150 people each year. Thatâ€™s more than sharks.',
'According to the Gemological Institute of America, up until 1896, India was the only source for diamonds to the world.',
'The shortest British monarch was Charles I, who was 4 feet 9 inches.',
'A rat can last longer without water than a camel.',
'40% of McDonaldâ€™s profits come from the sales of Happy Meals.',
'Christmas was once illegal in England.',
'No word in the English language rhymes with â€œMONTHâ€.',
'Women blink nearly twice as much as men.',
'The average human eats 8 spiders in their lifetime at night.',
'American Airlines saved $40,000 in 1987 by taking out an olive from First Class salads.',
'A creep is a metallurgical term for when something that is normally very strong bends because of gravity. This happens to many metals at high temperatures, where they wonâ€™t melt but they will creep.',
'The Australian $5 to $100 notes are made of plastic.',
'Every person, including identical twins, has a unique eye & tongue print along with their finger print.',
'Sweden has the least number of murders annually.',
'The dot over the letter â€œiâ€ is called a tittle.',
'A manned rocket reaches the moon in less time than it took a stagecoach to travel the length of England.',
'In England, in the 1880s pants was considered a dirty word.',
'In Paris, the McDonalds big â€˜Mâ€™ is the only one in the world that is white, rather than yellow, it was thought that yellow was too tacky.',
'Earth is the only planet not named after a god.',
'A group of goats is called a Trip.',
'If the Earth was smooth, the ocean would cover the entire surface to a depth of 12,000 feet.',
'Wearing headphones for just an hour will increase the bacteria in your ear by 700 times.',
'The first CD pressed in the US was Bruce Springsteenâ€™s â€œBorn in the USA.â€',
'Rubber bands last longer when refrigerated.',
'Antarctica is the only continent on which no Lepidoptera have been found.',
'Al Caponeâ€™s business card said he was a used furniture dealer.',
'â€œIthyphallophobiaâ€ is a morbid fear of seeing, thinking about or having an erect penis.',
'Americans on average eat 18 acres of pizza every day.',
'In the Durango desert, in Mexico, thereâ€™s a creepy spot called the Zone of Silence. You canâ€™t pick up clear TV or radio signals. And locals say fireballs sometimes appear in the sky.',
'The worldâ€™s youngest parents were 8 and 9 and lived in China in 1910.',
'Sigmund Freud had a morbid fear of ferns.',
'There are 336 dimples on a regulation US golf ball. In the UK its 330.',
'Maine is the only state (in USA) whose name is just one syllable.',
'When young, black sea basses are mostly female, but at the age of 5 years many switch sexes to male.',
'In the 17th century, the value of pi was known to 35 decimal places. Today, to 1.2411 trillion.',
'Women blink nearly twice as much as men.',
'Each year in America there are about 300,000 deaths that can be attributed to obesity.',
'Because of the rotation of the earth, an object can be thrown farther if it is thrown west.',
'Jimmy Carter was the first U.S. President to be born in a hospital.',
'Facetious and abstemious contain all the vowels in the correct order, as does arsenious, meaning containing arsenic.',
'160 cars can drive side by side on the Monumental Axis in Brazil, the worldâ€™s widest road.',
'Mongolia is the largest landlocked country.',
'Maine is the only state (in USA) whose name is just one syllable.',
'When young, black sea basses are mostly female, but at the age of 5 years many switch sexes to male.',
'In the 17th century, the value of pi was known to 35 decimal places. Today, to 1.2411 trillion.',
'Women blink nearly twice as much as men.',
'Each year in America there are about 300,000 deaths that can be attributed to obesity.',
'Women blink nearly twice as much as men.',
'Some lions mate over 50 times a day.',
'California has issued 6 drivers licenses to people named â€œJesus Christ.â€',
'Chinaâ€™s largest city is Shanghai.',
'More people are afraid of open spaces (kenophobia) than of tight spaces (claustrophobia).',
'A polar bears skin is black. Its fur is actually clear, but like snow it appears white.',
'A Boeing 747s wingspan is longer than the Wright brotherâ€™s first flight.',
'Butterflies can see red, green, and yellow.',
'A â€œjiffyâ€ is the scientific name for 1/100th of a second.',
'The 57 on the Heinz ketchup bottle represents the number of pickle types the company once had.',
'China has more English speakers than the United States.',
'In the UK, there is no act of parliament making it illegal to commit murder. Murder is only illegal due to legal precedent.',
'There are about 2 chickens for every human in the world.',
'Of all the words in the English language, the word â€˜setâ€™ has the most definitions!',
'Sex is biochemically no different from eating large quantities of chocolate.',
'Lee Harvey Oswaldâ€™s cadaver tag sold at an auction for $6,600 in 1992.',
'There is an average of 61,000 people airborne over the US at any given moment.',
'According to Douglas Adams, a Salween is the faint taste of dishwashing liquid in a cup of fresh tea.',
'A sizable oak tree, during the typical growing season, gives off 28,000 gallons of moisture.',
'Dendrology is the study of trees.',
'Louisianaâ€™s capital building is the tallest one of any U.S. state.',
'You are more likely to be killed by a champagne cork than by a poisonous spider.',
'Chevrolet tried marketing a Chevrolet Nova in Spanish speaking countries â€“ it didnâ€™t sell well because NOVA means â€œdoesnâ€™t goâ€ in Spanish.',
'A castrated male reindeer is called a bull.',
'Alabama was the first state to recognize Christmas as an official holiday.',
'A full moon always rises at sunset.',
'A group of owls is called a parliament.',
'There is a 1 in 4 chance that New York will have a white Christmas.',
'The placement of a donkeyâ€™s eyes in itâ€™s head enables it to see all four feet at all times!',
'In 1386, a pig in France was executed by public hanging for the murder of a child',
'Tasmania, Australia has the cleanest air in the inhabited world.',
'Iguanas, koalas and Komodo dragons all have two penises.',
'Butterflies and insects have their skeletons on the outside of their bodies, called the exoskeleton. This protects the insect and keeps water inside their bodies so they donâ€™t dry out.',
'In York, it is perfectly legal to shoot a Scotsman with a bow and arrow (except on Sundays)',
'John Lennonâ€™s first girlfriend was named Thelma Pickles.',
'A blind chameleon still changes colors to match his environment.',
'The Portuguese jellyfish tentacles have been known to grow a mile in length, catching anything in itâ€™s path by stinging itâ€™s prey.',
'Icelanders consume more Coca-Cola per Capita than any other nation.',
'A hedgehogâ€™s heart beats 300 times a minute on average.',
'Dueling is legal in Paraguay as long as both parties are registered blood donors.',
'Your brain generates 25 watts of power while youâ€™re awake. This amount of energy is enough to illuminate a lightbulb.',
'In an analysis of 200000 ostriches over 80 years, not one tried to bury its head in the sand.',
'The first toilet ever seen on television was on â€œLeave It to Beaver.â€',
'In ancient Greece â€œidiotâ€ meant a private citizen or layman.',
'In Jasmine, Saskatchewan, it is illegal for a cow to moo within 300 km of a private home.',
'Because of a large orbital eccentricity, Pluto was closer to the sun than Neptune between January 1979 and March 1999.',
'In Hartford, Connecticut, it is illegal for a husband to kiss his wife on Sundays.',
'One in every 9000 people is an albino.',
'Most household dust is made of dead skin cells.',
'A cockroach will live nine days without its head before it starves to death.',
'During his entire life, Vincent Van Gogh sold exactly one painting, â€œRed Vineyard at Arlesâ€.',
'Certain species of male butterflies produce scents that serve in attracting females during courtship.',
'There are no clocks in Las Vegas gambling casinos.',
'Male bees will try to attract sex partners with orchid fragrance.',
'On a Canadian two-dollar bill, the American flag is flying over the Parliament Building.',
'The crack of a whip is actually a tiny sonic boom, since the tip breaks the sound barrier.',
'Jupiter is bigger than all the other planets in our solar system combined.',
'Hot water is heavier than cold.',
'Lawn darts are illegal in Canada.',
'There are more psychoanalysts per capita in Buenos Aires than any other place in the world.',
'There is a town in Newfoundland, Canada called Dildo.',
' All 50 states are listed across the top of the Lincoln Memorial on the back of the $5 bill.',
'In space, astronauts are unable to cry, because there is no gravity and the tears wonâ€™t flow.',
'Chewing gum while peeling onions will keep you from crying.',
'There are more plastic flamingos in the U.S that there are real ones.',
'The world record for spitting a watermelon seed is 65 feet 4 inches.',
'In the Philippine jungle, the yo-yo was first used as a weapon.',
'Dueling is legal in Paraguay as long as both parties are registered blood donors.',
]

module.exports = facts